replacementMap = {
    'Љ': 'Lj',
    'Њ': 'Nj',
    'Е': 'E',
    'Р': 'R',
    'Т': 'T',
    'З': 'Z',
    'У': 'U',
    'И': 'I',
    'О': 'O',
    'П': 'P',
    'Ш': 'Š',
    'Ђ': 'Đ',
    'Ж': 'Ž',
    'А': 'A',
    'С': 'S',
    'Д': 'D',
    'Ф': 'F',
    'Г': 'G',
    'Х': 'H',
    'Ј': 'J',
    'К': 'K',
    'Л': 'L',
    'Ч': 'Č',
    'Ћ': 'Ć',
    'Џ': 'Dž',
    'Ц': 'C',
    'В': 'V',
    'Б': 'B',
    'Н': 'N',
    'М': 'M',
    'љ': 'lj',
    'њ': 'nj',
    'е': 'e',
    'р': 'r',
    'т': 't',
    'з': 'z',
    'у': 'u',
    'и': 'i',
    'о': 'o',
    'п': 'p',
    'ш': 'š',
    'ђ': 'đ',
    'ж': 'ž',
    'а': 'a',
    'с': 's',
    'д': 'd',
    'ф': 'f',
    'г': 'g',
    'х': 'h',
    'ј': 'j',
    'к': 'k',
    'л': 'l',
    'ч': 'č',
    'ћ': 'ć',
    'џ': 'dž',
    'ц': 'c',
    'в': 'v',
    'б': 'b',
    'н': 'n',
    'м': 'm'
}


def to_latin(text):
    """Turns all cyrillic to latin. I need this to mix serbian with other sister languages."""
    for key in replacementMap:
        text = text.replace(key, replacementMap[key])
    return text
